export const ADD_CONTACT = 'ADD_CONTACT';
export const FILTER_CONTACT = 'FILTER_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const SET_CURRENT_CONTACT = 'SET_CURRENT_CONTACT';
export const SET_WEATHER = 'SET_WEATHER';
export const GOT_WEATHER = 'GOT_WEATHER';
export const GOT_WEATHER_ERROR = 'GOT_WEATHER_ERROR';
export const NEW_CONTACT_CITY = 'NEW_CONTACT_CITY';
